# Generated by Django 5.2.12 on 2026-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('item_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('features_en', models.TextField(blank=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('rating_number', models.IntegerField(default=0)),
                ('categories_en', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'item_detail',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('title_ru', models.CharField(blank=True, default='', max_length=512)),
                ('year', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(db_table='movie_genre', related_name='movies', to='moviegeeks.genre')),
            ],
        ),
    ]
